Use new alloc (instead of node alloc).
Otherwise we get the following error because __node_alloc doesn’t seem
to define _M_allocate() or _M_deallocate():

sketch/stlport_test.ino.cpp.o: In function
`std::__node_alloc::allocate(unsigned int&)':
/Users/mellis/Documents/Arduino/libraries/stlport-avr/stl/_alloc.h:163:
undefined reference to `std::__node_alloc::_M_allocate(unsigned int&)'
sketch/stlport_test.ino.cpp.o: In function
`std::__node_alloc::deallocate(void*, unsigned int)':
/Users/mellis/Documents/Arduino/libraries/stlport-avr/stl/_alloc.h:166:
undefined reference to `std::__node_alloc::_M_deallocate(void*,
unsigned int)'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling.